In [1]:
#Exercícios de fixação de Numpy

In [2]:
import numpy as np

In [4]:
#Criando uma matriz 1D com números de 0 a 9

array = np.array([0,1,2,3,4,5,6,7,8,9])
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Criando uma matriz booleana 3x3 com 'True'

mt_bool = np.array([[True,True,True],
                   [True, True, True],
                   [True, True, True]])

mt_bool

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [38]:
#E#xtraindo todos os números ímpares de 'arr'

arr = np.array([0,1,2,3,4,5,6,7,8,9])
valores_impares = [x for x in arr if x % 2 != 0]
arr = np.array(valores_impares)
arr

array([1, 3, 5, 7, 9])

In [40]:
# Substituindo todos os números ímpares arr por -1

arr = np.array([0,1,2,3,4,5,6,7,8,9])
for i, v in enumerate(arr):
    if v % 2 != 0:
        arr[i] = -1
    else:
        None
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [45]:
# Substituindo todos os números ímpares em arr com -1 sem alterar arr

arr = np.array([0,1,2,3,4,5,6,7,8,9])
new_arr = arr.copy()

for i, v in enumerate(new_arr):
    if v % 2 != 0:
        new_arr[i] = -1
    else:
        None
print('arr', arr)
print('new_arr', new_arr)

arr [0 1 2 3 4 5 6 7 8 9]
new_arr [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [83]:
# Convertendo uma matriz 1D para uma mtriz 2D de duas linhas

arr = np.arange(0,10)
arr = arr.reshape((2, 5))
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
# Empilhando matrizes verticalmente

a = np.arange(10).reshape(2, -1) # Matriz com 10 elementos de 0 a 9
b = np.repeat(1, 10).reshape(2,-1) # Matriz com 10 elementos iguais a 1

new_matriz = np.concatenate((a,b), axis=0)
new_matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [103]:
# Empilhando matrizes horizontalmente

a = np.arange(10).reshape(2, -1) # Matriz com 10 elementos de 0 a 9
b = np.repeat(1, 10).reshape(2,-1) # Matriz com 10 elementos iguais a 1

new_matriz = np.concatenate((a,b), axis=1)
new_matriz

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [120]:
# Criado um padrão com base na matriz 'a'

a = np.array([1,2,3])
b = np.repeat(((1,1,1), (2,2,2), (3,3,3)), 1)
c = np.concatenate((b, a, a, a), axis = 0)
c

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [179]:
# Exercícios relacionados ao dataset Irís

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

sepallenght.max()

7.9

In [180]:
# Filtrando as linhas de iris_2d que possuem petallength (coluna 3) > 1.5 e sepallenght (coluna 1) < 5.0

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

sepallength_lower = list([x for x in iris_2d[:, 0] if x < 5.0])
petallength_larger = list([ x for x in iris_2d[:, 2] if x > 1.5])

In [184]:
# Selecionando as linhas de iris_2d que não tem nenhum valor 'Nulo'

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [2]:
# Calculando a quantidade de vezes que um número aparece em cada linha da matriz

#Exemplo: na linha [9,9,4,8,8,1,5,3,6,3]
# Vamos criar uma linha com a frequência de cada número, sendo de 1 a 10
# [1,0,2,1,1,0,0,2,2,0] está é a frequência em que os números aparecem
#  1 2 3 4 5 6 7 8 9 10

from operator import itemgetter
import numpy as np

arr = np.random.randint(1,11, size=(6,10))
new_array = np.zeros((6,10))
n = 0

while(n < 6):
    dic = {}
    for i in arr[n,:]:
        if i in dic:
            dic[i] = dic[i] + 1
        else:
            dic[i] = 1
    
        for k, v in zip(dic, dic.values()):
            new_array[n, k-1] = v
    n = n + 1

#dic = dict(sorted(dic.items(), key=itemgetter(0), reverse=False))

In [3]:
arr

array([[ 3,  2, 10,  1,  4,  3,  6,  5,  8,  5],
       [ 9,  1,  4,  8,  5,  4,  5, 10,  2,  3],
       [ 4,  1,  5,  4, 10, 10,  5,  7,  4,  4],
       [ 7,  4,  4,  2,  4,  7,  9, 10,  3, 10],
       [10,  4,  8,  9,  8,  1,  5,  9,  9,  5],
       [ 8,  9,  6, 10,  3,  3,  3,  6,  6, 10]])

In [4]:
new_array

array([[1., 1., 2., 1., 2., 1., 0., 1., 0., 1.],
       [1., 1., 1., 2., 2., 0., 0., 1., 1., 1.],
       [1., 0., 0., 4., 2., 0., 1., 0., 0., 2.],
       [0., 1., 1., 3., 0., 0., 2., 0., 1., 2.],
       [1., 0., 0., 1., 2., 0., 0., 2., 3., 1.],
       [0., 0., 3., 0., 0., 3., 0., 1., 1., 2.]])

In [295]:
# Encontrando todos os picos em uma matriz 1D numpy 'a'. Picos são pontos cercados por valores menores em ambos os lados

a = np.array([1, 8, 9, 1, 2, 10, 0, 1])
b = a.argmax()
a = np.delete(a, b)
c = a.argmax() + 1

picos = np.array([b,c])
picos

array([5, 3])